#pragma once

enum MessageType
{
	S2CH_SUCCESS_CONNECTED = 200,
	C2S_CLIENT_REQ,
	H2S_HOST_REQ,
	H2S_GET_USERINFO_LIST,
	S2H_GET_USERINFO_LIST_RES,
	C2S_CLIENT_DATA,
	S2H_CLIENT_DATA_REQ
};